name: task3
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev for private packages.
publish_to: 'none'

# Defines the version and build number for your application.
# Format: version: MAJOR.MINOR.PATCH+BUILD
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages your package needs to work.
dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: League Spartan
      fonts:
        - asset: assets/fonts/LeagueSpartanRegular.ttf
          weight: 400
